### Importing Required Libraries

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

### Creating Linear Regression Class

In [2]:
class LinearRegression:
    def __init__(self,learning_rate=0.01,iterations=None):
        self.lr=learning_rate
        self.iterations=iterations
        
    def fit(self,x,y):
        self.x=np.hstack((np.ones((x.shape[0],1)),x))
        self.y=y
        self.theetas=np.random.randint(1,6,size=(x.shape[1]+1,1))

    def Get_parameters(self):
        return self.theetas

    def train(self):
        # If user did not set any iterations, then finish when loss is constant or relative error is less than certain threshold (I kept it 0.01)
        if self.iterations == None :
            self.prev_loss=float('inf')
            while True:
                self.y_predicted=np.dot(self.x,self.theetas)
                self.loss=(1/(2*self.x.shape[0]))*np.sum((self.y-self.y_predicted)**2)
                if abs(self.prev_loss-self.loss) < 0.0001:
                    break
                self.prev_loss=self.loss
                self.partial_derivative_wrt_theetas = -(2/self.x.shape[0])*np.dot(self.x.T,(self.y-self.y_predicted))
                self.theetas=self.theetas - (self.lr*self.partial_derivative_wrt_theetas)

        # If user did set up max number of iterations, then finish on that
        else:
            for iteration in range(0,self.iterations):
                self.y_predicted=np.dot(self.x,self.theetas)
                self.loss=(1/(2*self.x.shape[0]))*np.sum((self.y-self.y_predicted)**2)
                self.partial_derivative_wrt_theetas = -(1/self.x.shape[0])*np.dot(self.x.T,(self.y-self.y_predicted))
                self.theetas=self.theetas - (self.lr*self.partial_derivative_wrt_theetas)

    def test(self,X_test,y_test):
        self.X_test=np.hstack((np.ones((X_test.shape[0],1)),X_test))
        self.y_predicted=np.dot(self.X_test,self.theetas)
        self.loss=(1/(2*self.X_test.shape[0]))*np.sum((y_test-self.y_predicted)**2)
        return self.loss

    def predict(self,X_test):  
        self.X_test=np.hstack((np.ones((X_test.shape[0],1)),X_test))
        return np.dot(self.X_test,self.theetas)


### Implementing Train Test Split

In [3]:
def train_test_split(X,y,test=0.2):

    train_size = X.shape[0]-int(X.shape[0]*test)
    permutations=np.random.permutation(X.shape[0])

    X=X[permutations]
    y=y[permutations]

    X_train = X[:train_size]
    y_train = y[:train_size]
    X_test = X[train_size:]
    y_test = y[train_size:]

    return X_train, X_test, y_train, y_test


### Loading Dataset and splitting it

In [4]:
diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target

### Splitting data using implemented train test split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y.reshape(-1,1),0.1)

### Fitting the data in the Linear Regression Model using 'fit' method

In [6]:
lr=LinearRegression(0.0001,1000000)
lr.fit(X_train,y_train)

### Training The model using 'train' method

In [7]:
lr.train()

### Printing the Final values of theetas by using Get_parameters function which return the value of trained weights

In [8]:
print(lr.Get_parameters())

[[151.9875856 ]
 [ 42.34328804]
 [ -8.48060054]
 [170.30653177]
 [117.65785579]
 [ 43.86648896]
 [ 31.20105128]
 [-92.77819031]
 [ 99.26926577]
 [149.41258922]
 [ 91.1567501 ]]


### Testing the model using 'test' method on testing data
### This method returns mean squared error on testing data

In [9]:
lr.test(X_test,y_test)

1593.2343235522326

### Predicting the output values against testing data using 'predict' method

In [10]:
y_predicted = lr.predict(X_test)

In [11]:
y_predicted

array([[135.59859521],
       [140.47983868],
       [200.7184282 ],
       [131.84100099],
       [118.10861846],
       [146.25838179],
       [111.90968043],
       [138.55173061],
       [161.98002046],
       [100.49871613],
       [151.52033824],
       [171.18991376],
       [152.70613249],
       [116.50558606],
       [185.05559713],
       [159.81397814],
       [186.50916517],
       [172.43470841],
       [219.60242651],
       [117.72239618],
       [157.15777431],
       [212.26401782],
       [175.44149301],
       [122.42289202],
       [140.26030586],
       [195.33918553],
       [182.07888545],
       [130.31845817],
       [108.79737215],
       [163.81211493],
       [154.18671867],
       [141.63411097],
       [161.13100643],
       [167.79745599],
       [107.37457688],
       [159.59805802],
       [187.93009016],
       [179.63772556],
       [156.47775366],
       [159.89322241],
       [138.62620473],
       [167.98271185],
       [179.13038234],
       [188

### Now using Linear Regression model without specifying hyperparameters (learning rate & maximum number of iterations)

In [12]:
lr=LinearRegression()
lr.fit(X_train,y_train)

lr.train()

print("Printing final values of theetas: \n")
print(lr.Get_parameters())
print("\n\n")

print("Printing MSE on testing data: \n")
print(lr.test(X_test,y_test))
print("\n\n")


print("Predicting labels for testing data: \n")
y_predicted = lr.predict(X_test)
print(y_predicted)

Printing final values of theetas: 

[[ 152.33679063]
 [  10.20502992]
 [-239.83408827]
 [ 536.49992125]
 [ 309.45646644]
 [ -47.23700892]
 [-116.3961801 ]
 [-196.14996793]
 [ 131.8020955 ]
 [ 442.81661234]
 [  82.93509394]]



Printing MSE on testing data: 

1268.5574262653722



Predicting labels for testing data: 

[[123.59983229]
 [144.72907449]
 [263.37127945]
 [125.80329476]
 [ 87.26142081]
 [109.18625872]
 [102.66454471]
 [106.73600772]
 [186.93711841]
 [ 65.80787364]
 [187.17461068]
 [176.64242993]
 [104.92934562]
 [ 87.33319396]
 [167.69068756]
 [174.40130865]
 [206.41597235]
 [204.28692962]
 [291.98720055]
 [ 69.29450684]
 [180.63407331]
 [236.76573267]
 [177.81993221]
 [ 79.17212172]
 [ 99.22753388]
 [219.88267944]
 [190.87825982]
 [ 79.77792392]
 [ 96.99748822]
 [190.35372545]
 [176.5391088 ]
 [120.17195109]
 [180.89338862]
 [210.51383313]
 [102.34599151]
 [140.45183872]
 [231.63176346]
 [200.17122669]
 [186.52573213]
 [183.18480797]
 [141.76140257]
 [162.20307442]
 [224.871